jenkins-x-plugins/jx-gitops

pkg/cmd/git/setup/setup.go, pkg/cmd/git/setup/test_data/expected.txt, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/requirement/merge/merge.go, pkg/cmd/requirement/merge/merge_test.go
so that Terraform can write to a ConfigMap the changes to the
jx-requirements.yml file and we can merge them into git inside the pipeline
=> fix: add ConfigMap support for merge

go.mod, go.sum, pkg/cmd/kpt/update/update.go, pkg/cmd/kpt/update/update_test.go
as the alpha-git-patch often fails
=> fix: switch default kpt update strategy

.goreleaser.yml, Makefile
as the arm binaries slow things down a fair bit
=> fix: add bigger timeout

go.mod, go.sum, pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/banzaicloud-stable/vault-operator/defaults.yaml, pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml, pkg/cmd/repository/export/export.go, pkg/sourceconfigs/helpers.go
=> fix: minor refactor

pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml, pkg/cmd/helmfile/template/test_data/helmfile.yaml, pkg/cmd/split/split.go, pkg/cmd/split/split_test.go, pkg/cmd/split/test_data/empty/empty-svc.yaml
to avoid kpt/jx gitops/kustomize failing on them later
=> fix: lets remove empty files

go.mod, go.sum, pkg/cmd/git/setup/setup.go, pkg/cmd/git/setup/setup_test.go
and ignore the current values to avoid using root as the git username
=> fix: always set the user/email for git

go.mod, go.sum, pkg/cmd/helmfile/template/template.go
on `jx gitops helm template` as we really don't need to see all those `wrote ....` lines from helm, they don't add any actual value
=> fix: lets make lots of output debug logging

pkg/cmd/pr/push/push.go
so it pushes to the correct branch (not the current BRANCH_NAME but the branch of the PR)
=> fix: push to branch logic

go.mod, go.sum, pkg/cmd/variables/variables.go, pkg/cmd/variables/variables_test.go
so that we generate nice sequential numbers by default for a nicer UX
=> fix: add a better BUILD_NUMBER generator

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-helmfile.yaml
also create the `.lighthouse/jenkins-x/*` files if an environemnt does not have them yet
=> fix: only perform custom upgrades if update mode

pkg/cmd/variables/variables.go
so we handle the new LH labels
=> fix: improve finding of the build number

docs/cmd/jx-gitops_helmfile_resolve.md, docs/cmd/jx-gitops_helmfile_template.md, docs/cmd/jx-gitops_pr_label.md, docs/config.md, docs/man/man1/jx-gitops-helmfile-resolve.1, docs/man/man1/jx-gitops-helmfile-template.1, docs/man/man1/jx-gitops-pr-label.1, go.mod, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/template/template.go, pkg/cmd/kpt/update/update.go, pkg/cmd/pr/label/label.go, pkg/cmd/upgrade/upgrade.go, pkg/helmhelpers/helpers.go, pkg/versionstreamer/versionstreamer.go
so that users don't have to install helm first
=> fix: use the helm plugin when upgrading git repos

pkg/cmd/scheduler/scheduler.go, pkg/cmd/scheduler/scheduler_test.go, pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/another-in-repo-sr.yaml, pkg/cmd/scheduler/test_data/versionStream/schedulers/another-in-repo.yaml, pkg/pipelinescheduler/builder.go, pkg/pipelinescheduler/scheduler_builder.go, pkg/pipelinescheduler/testhelpers/helpers.go, pkg/schedulerapi/types.go
so that local schedulers overwrite any versionStream/schedulers files
* allow 'in_repo: true' in a Scheduler
=> fix: lets override the versionStream/schedulers files with schedulers

pkg/cmd/git/get/get.go
to help fix/diagnose the preview gc issue
=> fix: improve discovery of environment git repository

pkg/cmd/plugin/plugin.go, pkg/cmd/plugin/upgrade/upgrade.go, pkg/cmd/root.go, pkg/cmd/webhook/verify/verify.go, pkg/plugins/helpers.go, pkg/plugins/helpers_test.go, pkg/plugins/versions.go
so we can easily download binary plugins in container images
=> fix: add binary plugin upgrade

pkg/plugins/versions.go
=> fix: disable kpt for plugin download

pkg/cmd/requirement/resolve/resolve.go, pkg/cmd/requirement/resolve/resolve_test.go
to a fully qualified name if not already defined
=> fix: default the chart repository

pkg/cmd/kpt/update/update.go
if the only merge conflict is on a Kptfile (which should never really happen) lets workaround it and carry on the git merge
=> fix: work around kpt getting a merge conflict on Kptfile

go.mod, go.sum, pkg/cmd/variables/variables.go
which was causing the PR build numbers to always be 1
=> fix: add fix for mixed case organisations/repos

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/expected-nginx-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/ingress-nginx/defaults.yaml, pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/ingress-nginx/values.yaml.gotmpl
=> fix: custom helmfile upgrade for new nginx chart

pkg/cmd/helmfile/resolve/resolve.go
=> fix: always regenerate the helmfile jx-values.yaml

go.mod, go.sum, pkg/cmd/git/git.go, pkg/cmd/git/merge/merge.go, pkg/cmd/git/merge/merge_shas.go, pkg/cmd/git/merge/merge_test.go, pkg/cmd/git/merge/pull_refs.go, pkg/cmd/git/merge/pull_refs_test.go
to remove the need for the v2 image/step
=> fixx: first spike of a git rebase/merge command

pkg/plugins/versions.go
so we can start trying it out instead of kubectl apply
=> fix: added kapp support

pkg/cmd/kpt/update/update.go, pkg/cmd/kpt/update/update_test.go
=> fix: lets only upgrade if git is clean

pkg/apis/gitops/v1alpha1/quickstart_types.go, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/extensions/quickstarts.yaml, pkg/matcher/matcher.go, pkg/quickstarthelpers/load.go
also lets upgrade the old .yml files for quickstarts to the new yaml layout
=> fix: move the quickstart parsing code here

pkg/cmd/jenkins/jobs/jobs.go
when we lazily create a jenkins server for the source config
=> fix: lets add the jenkins version stream config

pkg/cmd/variables/variables.go
=> fix: ensure we have a valid branch for gitops variables

go.mod, go.sum, pkg/cmd/jenkins/add/add.go, pkg/cmd/jenkins/add/add_test.go, pkg/cmd/jenkins/add/test_data/helmfile.yaml, pkg/cmd/jenkins/add/test_data/jx-requirements.yml, pkg/cmd/jenkins/add/test_data/versionStream/charts/repositories.yml, pkg/cmd/jenkins/jobs/jobs.go, pkg/sourceconfigs/helpers.go
so that future quickstarts/imports can reuse the jenkins server
=> fix: adding a jenkins server adds an entry in the source config

go.mod, go.sum, pkg/cmd/git/setup/setup.go
=> fix: allow git setup command to use custom password

pkg/cmd/git/setup/setup.go
so we can use this step in github actions
=> fix: make 'jx gitops git setup' usable in GHA

pkg/cmd/plugin/upgrade/upgrade.go, pkg/cmd/variables/variables_test.go
to see if this is the cause of cloudbuild failures to make jx-cli jx-boot image
=> chore: temporary disable of helm-x install

go.mod, go.sum
to better support bitbucket cloud
=> fix: upgrade deps

go.mod, go.sum, pkg/cmd/webhook/update/update.go
bitbucket cloud doesn't support hmac yet
=> fix: handle missing hmac secret if using BBC

go.mod, go.sum, pkg/cmd/webhook/update/update.go
avoid bug in annotate logic and error handling
which caused the annotation to fail
=> fix: annotate logic

pkg/cmd/helmfile/report/markdown.go, pkg/cmd/helmfile/report/markdown_test.go, pkg/cmd/helmfile/report/report.go, pkg/cmd/helmfile/status/status.go, pkg/releasereport/helpers.go, pkg/releasereport/types.go
so its easier to reuse in other plugins
=> fix: refactor the release report library

pkg/cmd/helmfile/report/report.go
=> fix: avoid failing if using OCI repository

pkg/cmd/requirement/merge/merge.go, pkg/cmd/requirement/merge/test_data/gke-ignore-env/changes.yml, pkg/cmd/requirement/merge/test_data/gke-ignore-env/expected.yml, pkg/cmd/requirement/merge/test_data/gke-ignore-env/jx-requirements.yml
=> fix: lets ignore terraform environment requirements

docs/cmd/jx-gitops_helmfile_resolve.md, docs/config.md, docs/man/man1/jx-gitops-helmfile-resolve.1, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/helmhelpers/helpers.go
to reuse the helmfile templating for user/pwd values
=> fix: use a better approach to adding helm repos

go.mod, go.sum, pkg/cmd/git/setup/setup_test.go, pkg/cmd/git/setup/test_data/expected2.txt, pkg/cmd/helmfile/report/report.go
handle relative chart paths better
=> fix: better jx-charter support

go.mod, go.sum, pkg/cmd/helmfile/report/report.go
to avoid assuming all conditionals are true
=> fix: lets only include report releases which are used

docs/config.md, docs/scheduler-config.md, pkg/cmd/helmfile/add/add.go, pkg/cmd/helmfile/add/add_test.go, pkg/cmd/helmfile/add/test_data/expected/helmfile.yaml, pkg/cmd/helmfile/add/test_data/expected/helmfiles/cheese/helmfile.yaml, pkg/cmd/helmfile/add/test_data/expected/helmfiles/jx/helmfile.yaml, pkg/cmd/helmfile/add/test_data/expected/helmfiles/nginx/helmfile.yaml, pkg/cmd/helmfile/add/test_data/input/helmfiles/nginx/helmfile.yaml, pkg/cmd/jenkins/add/add.go, pkg/cmd/jenkins/add/test_data/helmfile.yaml, pkg/cmd/jenkins/jobs/jobs_test.go, pkg/cmd/jenkins/jobs/test_data/hasjobs/helmfile.yaml, pkg/cmd/variables/variables_test.go, pkg/helmfiles/add.go, pkg/helmfiles/add_test.go, pkg/helmfiles/editor.go, pkg/helmfiles/helpers.go, pkg/helmfiles/testhelmfile/helpers.go
to reuse the new multi-helmfile aware editor
=> dd fix: refactor the helmfile add command

go.mod, go.sum, pkg/helmfiles/add.go
so that we can just update versions without adding new charts when using sync
=> fix: support update only mode

pkg/cmd/git/setup/setup.go
=> fix: lets allow the requirements to be passed in

pkg/apis/gitops/v1alpha1/quickstart_types.go
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> feat: Add mlprojectsets

pkg/sourceconfigs/helpers.go
=> fix: make group owner lowercase for comparison

pkg/cmd/webhook/delete/delete.go, pkg/cmd/webhook/webhook.go
Tried to make this as safe as possible.
By default a filter needs to be specified or all-webhooks needs to be false.
Dry-run is also enabled by default.
=> feat: jx gitops webhook delete

Dockerfile-preview, go.mod, pkg/cmd/gc/activities/activities.go, pkg/cmd/gc/activities/activities_test.go
=> fix: delete tekton pipelineruns when pas are gc'ed

pkg/cmd/gc/activities/activities.go
=> fix: check for error when deleting tkn prs

pkg/cmd/gc/activities/activities.go
=> fix: delete lj and tkn prs for pas which exceed revision history

pkg/cmd/plugin/upgrade/upgrade.go, pkg/plugins/versions.go
Continuing from the previous PR (#806) this PR adds the functionality to install the helm-s3 plugin
=> feat: Install/upgrade helm-s3 plugin

pkg/cmd/gc/activities/activities.go
=> fix: only warn on not being able to delete pipelineruns

go.mod, go.sum
=> chore: bump lighthouse client to 0.0.295

pkg/tfupgrade/test_data/eks/expected.tf, pkg/tfupgrade/test_data/eks/main.tf, pkg/tfupgrade/test_data/eks/versionStream/git/github.com/jenkins-x/terraform-aws-eks-jx.yml, pkg/tfupgrade/tfupgrade.go, pkg/tfupgrade/tfupgrade_test.go
=> fix: eks git ops tf upgrade

pkg/cmd/helm/release/release.go
Username and password are not supplied for neither s3 nor gcs. So there is no reason to exit with error if they are missing in those cases.
=> fix: Don't require password unnecessarily

.github/workflows/codeql-analysis.yml, .lighthouse/jenkins-x/pullrequest.yaml, .lighthouse/jenkins-x/release.yaml
Hey @ankitm123, I tried to create the codeql file can you review it
=> fix: created codeql-analysis.yml

pkg/cmd/git/merge/merge_shas.go, pkg/cmd/helmfile/move/move.go
=> fix: Correct namespace for resources

pkg/plugins/versions.go
Reverts jenkins-x-plugins/jx-gitops#854
PR needs some more work
=> Revert "chore(deps): Upgrade kpt"

.lighthouse/jenkins-x/release.yaml
Reverts jenkins-x-plugins/jx-gitops#860
=> Revert "fix: Resources for release build"

pkg/cmd/apply/apply.go
Fixes jenkins-x/jx3-versions#2731
I also added NEW_CLUSTER variable for regen targets which will be useful for jenkins-x/jx3-versions#3223
=> fix: Regen on new cluster

cmd/app/main-win.go, cmd/app/main.go, pkg/cmd/gc/activities/activities_test.go, pkg/cmd/git/merge/pull_refs_test.go, pkg/cmd/helm/release/release.go, pkg/cmd/helm/release/release_test.go, pkg/cmd/helm/release/testdata/pages/README.md, pkg/cmd/requirement/edit/edit_test.go, pkg/pipelinescheduler/builder_test.go, pkg/pipelinescheduler/config_builder_test.go
Resolves #879
Signed-off-by: Hays Clark <hays.clark@gmail.com>
=> feat: include chart name and version in commits for pages chart repos

pkg/cmd/helmfile/report/markdown.go, pkg/cmd/helmfile/report/testdata/expected.README.md
Don't add empty links
Add sources as source links
=> fix: Show links better

pkg/cmd/apply/apply.go
=> revert: Regen on new cluster

pkg/sourceconfigs/helpers.go, pkg/sourceconfigs/helpers_test.go
=> fix: replace / in nested gitlab repos with - to fix slack issues

.lighthouse/jenkins-x/release.yaml
Trying to fix that goreleaser times out
=> fix: Resources for release build

.github/workflows/plugins-pr.yaml, Makefile, go.mod, go.sum
https://github.com/jenkins-x/jx/issues/8283
=> fix: upgrade go to the latest go1.18

pkg/pipelinecatalogs/pipelinecatalogs.go
=> fix: use jenkins x org as default for pipeline catalog

pkg/helmfiles/add.go
=> fix: new boolean variable to fix chart adding logic

pkg/cmd/helm/release/release.go, pkg/cmd/helm/release/release_test.go
I have tested this and it can deploy to AWS ECR registry.
It needs the docker-credential helpers available on the path and credentials  to push to OCR registry. Similar to how regular containers are pushed to registry. So some changes to how the image that runs this is needed.
=> fix: helm release login not needed when using OCI + docker-credential-helpers.

pkg/cmd/helmfile/status/status.go, pkg/cmd/helmfile/status/status_test.go
Fixes #866 
The PR replaces #867
=> fix: set inactive deployment status & skip deployments that are unchanged 

pkg/cmd/pr/push/push.go
Make force push more lenient so new commits on branch doesn't get overwritten
=> fix: force push pr with lease

pkg/cmd/helmfile/status/status.go
If the convention that the chart has the same name as the repo is followed the logic in `helmfile status` fails. One valid cause could be that there are multiple charts in one repo.
=> Support using repo from chart sources for setting deployment status

pkg/cmd/helmfile/status/status.go, pkg/cmd/helmfile/status/status_test.go, pkg/cmd/helmfile/status/testdata/docs/releases.yaml
Fix to make it work like intended in #920
=> fix: correct sign of offset and negation of expression

pkg/cmd/helmfile/status/status.go, pkg/cmd/helmfile/status/status_test.go
This fixes a regression in #867 / #919 that means than new versions are not registered
=> fix: create new deployment on new ref

pkg/cmd/pr/variables/variables.go
Fixed the issue of only getting the first page of comments.
=> fix:  get comments

pkg/cmd/apply/apply.go
=> fix: no regen on new cluster

pkg/cmd/apply/apply.go, pkg/cmd/apply/apply_test.go
Some improved tests that catch the problem that was solved with #947
/cc @tomhobson
=> fix: add test for no regen on new cluster

go.mod, go.sum, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/testdata/replace-chart/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart/helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart/jx-requirements.yml, pkg/cmd/helmfile/resolve/testdata/replace-chart/versionStream/charts/jxgh/pusher-wave/defaults.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart/versionStream/charts/repositories.yml, pkg/cmd/helmfile/resolve/testdata/replace-chart/versionStream/charts/wave-k8s/wave/defaults.yaml
This depends on jenkins-x/jx-helpers#417
=> feat: replace chart

pkg/plugins/versions.go
Upgrade helm version with bug fixes, especially needed for: https://github.com/helm/helm/issues/12835
=> chore: upgrade default helm version to 3.15.1

Makefile, pkg/cmd/gc/gc.go, pkg/cmd/git/git.go, pkg/cmd/git/merge/merge_test.go, pkg/cmd/helm/helm.go, pkg/cmd/helmfile/helmfile.go, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/jx-requirements.yml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/versionStream/charts/bank-vaults/vault-operator/defaults.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/versionStream/charts/banzaicloud-stable/vault-operator/defaults.yaml, pkg/cmd/helmfile/resolve/testdata/replace-chart-oci/versionStream/charts/repositories.yml, pkg/cmd/jenkins/jenkins.go, pkg/cmd/kpt/kpt.go, pkg/cmd/kpt/recreate/recreate.go, pkg/cmd/plugin/plugin.go, pkg/cmd/pr/pr.go, pkg/cmd/repository/repository.go, pkg/cmd/requirement/requirement.go, pkg/cmd/root.go, pkg/cmd/sa/sa.go, pkg/cmd/webhook/delete/delete.go, pkg/cmd/webhook/update/update.go, pkg/cmd/webhook/webhook.go, pkg/helmfiles/add.go, pkg/helmfiles/helpers.go, pkg/pipelinescheduler/config_builder.go
Supporting both adding repository from version stream and helmfile add command
Also drying upp the code a bit
Part of fix for jenkins-x/jx#8688
=> feat: handle adding oci helm repository

go.mod, go.sum, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/testdata/no-jx-values/expected-cert-manager-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/no-jx-values/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/no-jx-values/helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/no-jx-values/jx-requirements.yml, pkg/cmd/helmfile/resolve/testdata/no-jx-values/versionStream/charts/jetstack/cert-manager/defaults.yaml, pkg/cmd/helmfile/resolve/testdata/no-jx-values/versionStream/charts/jetstack/cert-manager/values.yaml.gotmpl, pkg/cmd/helmfile/resolve/testdata/no-jx-values/versionStream/charts/repositories.yml, pkg/helmhelpers/constants.go
Part of better fix for helm chart schema problem
=> feat: apply default labels and skip jx-values.yaml in values

pkg/cmd/helmfile/move/move.go
range is iterating through map in random order. Switching to slice.
=> fix: make order of annotations stable

.lighthouse/jenkins-x/release.yaml
reverting sbom signing since it isn't working
also reverting setting golang image since the default should work now
=> fix: make release work

go.mod, go.sum, pkg/apis/scheduler/v1alpha1/types.go, pkg/pipelinescheduler/builder.go, pkg/pipelinescheduler/config_builder.go
Related to https://github.com/jenkins-x/lighthouse/pull/1641
=> feat: allow display report completion duration

pkg/cmd/upgrade/upgrade.go
The main purpose of this feature is to use it to fill the pull request body when jx-updatebot env create a PR for upgrading a cluster.
=> feat: save release notes to file

pkg/cmd/helmfile/move/move.go
The main purpose of this is to be able to skip helm tests by adding the arguments `--invert-selector --selector-target metadata.annotations --selector helm.sh/hook=test`
Since the arguments are parsed already it seems like there have been a plan to implements this before.
=> feat: support filtering move

.lighthouse/jenkins-x/release.yaml
Reverts jenkins-x-plugins/jx-gitops#1021
=> Revert "chore: debug release problem"

pkg/cmd/git/merge/merge_test.go, pkg/ghpages/ghpages.go
=> fix: ensure git user is configured for ghpages
