pkg/cmd/apps/resolve/resolve.go, pkg/cmd/apps/resolve/test_data/expected-jx-apps.yml, pkg/jxtmpl/reqvalues/requirements_values.go
due to some bugs around version stream dir handling
also moved to the nicer named file `jx-values.yaml` which is the file we can pass into helm charts
=> fix: some gremlins on the apps resolve

.goreleaser.yml
=> chore: disable arm builds for now

jenkins-x.yml, pkg/cmd/requirement/merge/merge.go, pkg/cmd/requirement/merge/test_data/expected.yml, pkg/cmd/requirement/merge/test_data/jx-requirements.yml
when we load the merge changes from Terraform we should not populate
default values like gitServer: "https://github.com" otherwise the merge
logic thinks Terraform is configuring the git server and we end up losing
the users gitServer value
so lets load the YAML file without applying any default values
=> fix: avoid overwriting the gitServer

pkg/cmd/helmfile/template/template.go, pkg/jxtmpl/reqvalues/requirements_values.go
so that production/staging charts have separate ingress host names if the same app is deployed to both namespaces and we are using a single cluster
we use a separate jx-values-$namespace.yaml file using the ingress from the `jx-requirements.yml` or a custom namespace specific subdomain
fixes #237
=> fix: support separate ingress domain / subdomain per namespace

pkg/cmd/scheduler/scheduler_test.go, pkg/cmd/scheduler/test_data/versionStream/schedulers/default.yaml, pkg/cmd/scheduler/test_data/versionStream/schedulers/environment.yaml, pkg/cmd/scheduler/test_data/versionStream/schedulers/in-repo.yaml, pkg/cmd/scheduler/test_data/versionStream/schedulers/jx-meta-pipeline.yaml, pkg/pipelinescheduler/builder.go, pkg/pipelinescheduler/config_builder.go, pkg/pipelinescheduler/scheduler_builder.go, pkg/pipelinescheduler/test_data/merger_with_mergemethod/parent.yaml, pkg/pipelinescheduler/test_data/merger_with_parent/parent.yaml, pkg/pipelinescheduler/test_data/multiple_contexts/repo.yaml, pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/parent.yaml, pkg/pipelinescheduler/test_data/only_with_parent/parent.yaml, pkg/pipelinescheduler/test_data/policy_with_parent/parent.yaml, pkg/pipelinescheduler/test_data/repo/repo.yaml, pkg/pipelinescheduler/test_data/with_parent/parent.yaml, pkg/pipelinescheduler/testhelpers/helpers.go, pkg/schedulerapi/types.go
so that we can keep presubmits purely in-repo and the rest can be centralised
=> fix: lets move the repo/merge/context options out of presubmits

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/upgrade/upgrade.go
so we can use `jx gitops upgrade` on any git repository - e.g. a quickstart
=> fix: only run helmfile resolve if we have a helmfile

pkg/cmd/apply/apply.go
if we merge a PR but we have not successfully regenerated we could skip the regen-2 phase
=> fix: avoid bug missing out regen-phase-2

go.sum, pkg/cmd/helmfile/resolve/resolve.go
this means we can install the same chart into different namespaces but configured with different helm values from a version stream
this is what keeps existing behaviour https://github.com/jenkins-x/jx-gitops/blob/1605cc7b845c0469f491768f219c63bf1a8da573/pkg/cmd/helmfile/resolve/resolve.go#L190-L192
=> chore: use the release name to resove values files, which defaults to the chart name if release name is not set, which keeps existing behaviour.

go.mod, go.sum, pkg/cmd/git/setup/setup.go
which loads the git credential from the tekton-git secret in the current namespace
=> fix: allow tekton-secret mode

pkg/jxtmpl/reqvalues/requirements_values.go
In order to use `condition` syntax in helmfile (https://github.com/roboll/helmfile/blame/88884b68dcbb0a5b01676e18bb53444cffa3c89b/README.md#L127) we need to output values in no more than two part notation due to the following logic in helmfile https://github.com/roboll/helmfile/blob/88884b68dcbb0a5b01676e18bb53444cffa3c89b/pkg/state/state.go#L1821
So we need to flatten our requirements hierarchies for anything we want to conditionally install via our helmfiles. Two obvious candidates that spring to mind are external-dns and cert-manager both of which we probably want to drive from our requirements file.
=> feat: Added in helmfile compatible conditional values for use in condition parameter of helmfile

pkg/cmd/kpt/update/update.go
avoid failing when kpt reports no updates which isn't really an error
=> fix: handle different case in kpt error messages

pkg/cmd/helm/escape/espape.go, pkg/cmd/helm/escape/espape_test.go, pkg/cmd/helm/escape/test_data/expected/config-observability-cm.yaml, pkg/cmd/helm/escape/test_data/src/config-observability-cm.yaml, pkg/cmd/helm/helm.go
so its easy to take any YAML which includes `{{` or `}}` (typically in sample `ConfigMap` data) and convert them so they can be packaged as helm charts
=> fix: add escape command

pkg/cmd/variables/variables.go
Also use imperative mood in the commit message. 'add' instead of 'added'.
=> chore(variables): add arg to skip committing `variables.sh`

pkg/cmd/helmfile/add/add.go, pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-tekton-pipelines-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/expected-foo-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/input/expected-tekton-pipelines-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-tekton-pipelines-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-external-secrets-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-foo-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-tekton-pipelines-helmfile.yaml, pkg/helmhelpers/helpers_test.go, pkg/jxtmpl/reqvalues/requirements_values.go
by using a namespace specific jx-values.yaml file for each namespace helmfile which contains the combination of requirements, global values and any fake secrets
ideally there would be a nice way to do this in helmfile without repeating the file name in the enivironment and in each chart; but until there is we have to do it this way
=> fix: support separate ingress domain per namespace

pkg/cmd/apply/apply.go, pkg/cmd/jenkins/add/add.go
so we can more easily reuse the pipeline git token
=> fix: lets add extra jenkins resources by default

pkg/cmd/webhook/verify/verify.go
The gitea webhook contains a secret parameter so use prefix match
fixes https://github.com/jenkins-x/jx-gitops/issues/476
=> fix: gitea webhook update creating duplicate hooks

pkg/cmd/helm/release/release.go
lint fails if a dependency is missing so...
Funny thing, this can't be circumvented by changing the pipeline to call `helm dependency build` before of `jx gitops helm release` because of https://github.com/helm/helm/issues/9164
=> fix: helm lint should be called after dependency build

go.mod, go.sum, pkg/cmd/helmfile/report/report.go
so it only fetches chart metadata for new charts or new versions so usually its super fast as usually most charts don't change
=> chore: make 'jx gitops helmfile report' fast

pkg/variablefinders/version.go
for pull requests to put the SNAPSHOT at the end so that things work better with maven repositories - we usually want any deployed snapshots to go to snapshot repositories
=> fix: improve default VERSION

go.mod, go.sum, pkg/cmd/pr/label/label.go
lets use a newer go-scm so that we register all the BitBucket Server webhooks
also lets query the labels if they don't appear on a PullRequest
=> fix: for bitbucket server

pkg/pipelinescheduler/config_builder.go, pkg/pipelinescheduler/test_data/merger_with_mergemethod/config.yaml, pkg/pipelinescheduler/test_data/merger_with_parent/config.yaml, pkg/pipelinescheduler/test_data/multiple_contexts/config.yaml, pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/config.yaml, pkg/pipelinescheduler/test_data/only_with_parent/config.yaml, pkg/pipelinescheduler/test_data/policy_with_parent/config.yaml, pkg/pipelinescheduler/test_data/repo/config.yaml, pkg/pipelinescheduler/test_data/with_parent/config.yaml
lighthouse uses its config to know if it should expose an internal http handler with prometheus metrics (on /metrics)
let's enable it by default - lighthouse is already taking care of using an internal http server for it, so it has no security impact (on the webhook server which might be exposed to everybody)
note that it's not enough to enable automatic scraping of the metrics by prometheus: for that, we need to add a specific label on the lighthouse pods
=> chore: expose prometheus metrics on lighthouse

go.mod, go.sum, pkg/cmd/helmfile/move/move.go, pkg/cmd/helmfile/move/move_test.go
so that we can more easily process namespace resources differently to
non-namespace cluster resources (e.g. to avoid pruning Namespaces by
default)
=> fix: lets put cluster resources into a sub dir

pkg/cmd/helmfile/report/report.go
=> fix: lets log a warning if a Chart.yaml is invalid

pkg/cmd/variables/variables.go
Ref: https://kubernetes.slack.com/archives/C9MBGQJRH/p1620116491200400
=> fix: warn instead of fail if 'jx gitops variables' is run in a folder without git

pkg/cmd/variables/variables.go
Fixes the current GIT\_BRANCH content since the merge of [this PR](https://github.com/jenkins-x-plugins/jx-gitops/pull/749):
> GIT\_BRANCH=fatal: not a git repository (or any parent up to mount point /)
=> fix: return empty string instead of the error message if not in a git directory

pkg/cmd/helmfile/resolve/resolve.go
as this breaks if an old chart repository is being used which prevents the
upgrade from fixing it up
=> fix: lets disable helmfile repos

pkg/cmd/git/clone/clone.go, pkg/cmd/git/get/get.go, pkg/cmd/git/merge/merge.go, pkg/cmd/git/setup/setup.go
This documentation has already been contributed [here](https://github.com/jenkins-x/jx-docs/pull/3335) but it was noted that it was misplaced. Here I have moved the documentation back into the source code.
=> chore: Move submitted doucmentation changes frox jx-docs to jx-gitops source code

pkg/cmd/variables/variables.go, pkg/cmd/variables/variables_test.go
Azure ACR and AWS ECR must have their name in lowercase, and since [putting the registry name in lowercase in jx-requirements](https://github.com/jenkins-x-terraform/terraform-jx-azure/pull/9) isn't enought, it's also put in lowercase in variables.sh, to avoid error at pipelines build time.
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#az-acr-login-succeeds-but-docker-fails-with-error-unauthorized-authentication-required
https://aws.amazon.com/en/ecr/ (see the first note)
=> fix: ensure the registry name is in lowercase

pkg/cmd/apply/apply.go
In gitlab， merge request message default like
```
Merge branch 'pr-cb3d0312-bdb0-496a-90ba-7e6f59d7afc7' into 'master'
chore: promote xxxxxxx to version 1.1.19
See merge request !500
```
This will cause the region run in pullrequst to be rerun after merge。
=> fix: compatible regen-phase with gitlab

pkg/chart/chart.go, pkg/cmd/helm/build/build.go, pkg/cmd/helm/release/release.go
This PR adds any repositories declared under `dependencies` in _Chart.yaml_ with `helm repo add` before running `helm repo build`. Without it the _promote-helm-release_ fails with a similar error when dependencies are needed:
```
no repository definition for https://charts.bitnami.com/bitnami. Please add the missing repos via 'helm repo add'
```
This PR only works with the v2 spec of _Chart.yaml_. If having a separate _requirements.yaml_ for dependencies, this PR won't have any effect.
=> chore: add helm repos before helm build

go.mod, go.sum, pkg/cmd/rename/rename.go, pkg/cmd/rename/rename_test.go, pkg/cmd/rename/test_data/resource-with-helm-templates.yaml
so that it can ignore the to template lines starting with `{{` when parsing
to find the resource name, kind, namespace
=> fix: allow rename to work with templated yaml

pkg/cmd/helm/release/release.go
When using github pages to publish the helm chart the username to github is now defaults to the owner (organisation) instead of the actual name of the user. This fixes that.
=> fix: Default username to user not owner

go.mod, go.sum, pkg/variablefinders/requirements.go
To ease reuse I'm splitting out GetSettings from FindRequirements. I will use GetSettings to get the issueTracker in jx-changelog.
=> refactor: Split out func GetSettings from FindRequirements

pkg/plugins/versions.go
The main reason for this PR is that in the last version of helmfile you can specify the value of .Capabilities.KubeVersion in template mode, which is necessary get some helm charts rendered correctly.
=> chore(deps): Upgrade helm and helmfile

pkg/plugins/versions.go
Seen issues with kubernetes version 1.20 with the current version, so backdating to allow users to have more choice in their selection of k8s versions. As we shouldn't be dictating which version of k8s our users are on.
=> fix: backdate version to increase kubernetes version compatability

pkg/cmd/namespace/namespace.go
Dirty fix, but may save some clusters.
https://kubernetes.slack.com/archives/C9MBGQJRH/p1647955769010979
https://github.com/jenkins-x/jx3-versions/pull/2963
Signed-off-by: Damian Kęska <372403+keskad@users.noreply.github.com>
=> fix: Do not recreate namespace `jx-git-operator`

pkg/cmd/namespace/namespace.go
Reverts jenkins-x-plugins/jx-gitops#836 - connected to revert https://github.com/jenkins-x-plugins/jx-gitops/pull/838
=> Revert "fix: Do not recreate namespace `jx-git-operator`"

pkg/cmd/helmfile/report/markdown.go, pkg/cmd/helmfile/report/report.go, pkg/cmd/helmfile/report/test_data/expected.README.md, pkg/cmd/helmfile/report/test_data/releases.yaml, pkg/releasereport/types.go
This covers the use case where a chart is deployed multiple times in the same namespace with different release names
(see https://kubernetes.slack.com/archives/C9LTHT2BB/p1619666560425000 for an examlple
=> fix: show both release and chart names in report

pkg/plugins/versions.go
I can't see in the docs that there are any breaking changes for kpt pkg, which as far as I know is the only functionality currently used by Jenkins-X. But I plan to use kpt live to solve jenkins-x/jx#8024 and those commands have breaking changes, so it would be easier to upgrade before starting to use that functionality.
=> chore(deps): Upgrade kpt

pkg/cmd/pr/variables/variables.go
This PR is the newly rebased version of this https://github.com/jenkins-x-plugins/jx-gitops/pull/805
This should fix the problem where trying to use  ` jx gitops pr variables --comments` - fails with 
```
error: failed to load variables from PR comments: failed to list comments of PR 91: Not Found
```
=> fix: pr comment variables

go.mod, go.sum, pkg/cmd/pr/variables/variables.go
Fix the issue of listcomments reading order in gitlab so that the latest variables can be read
=> fix:  ListComments order of gitlab

pkg/sourceconfigs/helpers.go, pkg/sourceconfigs/helpers_test.go
Issue from jx-slack where it doesn't find configuration for one of my repositories
I have repositories, splitted into 2 different groups just because it doesn't use the same scheduler
on the case the kind, gitserver url and owner is the same on both group, the function GetOrCreateGroup will just take the first group, even if my repository is on the second one
in order to fix this I have- create Get only function in order to get the right repository on jx-slack
=> chore: add GetFilteredGroups GetRepository GetRepositoryFor

pkg/plugins/versions.go
While we wait for the upstream helmfile/helmfile repo to stabilize for https://github.com/jenkins-x-plugins/jx-gitops/pull/869, I'd like to leverage the `--skip-tests` feature released in [version 0.143.1](https://github.com/roboll/helmfile/releases/tag/v0.143.1). 0.144.0 is the most recent version available from the roboll/helmfile remote.
ref https://github.com/jenkins-x/jx3-versions/pull/3306
=> chore: upgrade helmfile plugin binary to 0.144.0

pkg/cmd/apply/apply.go
Fixes https://github.com/jenkins-x/jx3-versions/issues/2731
I also added NEW_CLUSTER variable for regen targets which will be useful for https://github.com/jenkins-x/jx3-versions/pull/3223
This is  a new attempt after #876 had to be reverted
=> fix: Regen on new cluster

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/resolve_test.go, pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/expected-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/jx-requirements.yml
Where a namespace is specified for an environment,
custom ingress settings (ingress.domain & ingress.nameSpaceSubDomain)
should be populated in jx-values for the namespaces
fixes https://github.com/jenkins-x/jx/issues/8514
=> fix: correct ingress details on custom namespaces

pkg/apis/gitops/v1alpha1/source_config_types.go
Useful to keep source-config.yml organised for example when having groups for different teams
=> fix: field to distinguish repository groups

pkg/plugins/versions.go
Especially to get rid of error in jx boot job
error: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"
Related to jenkins-x/jx#8454
=> fix: upgrade kubectl

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/testdata/remote-chart/expected-foo-helmfile.yaml, pkg/helmfiles/helpers.go, pkg/helmfiles/helpers_test.go, pkg/helmfiles/helpers_test_data/helmfile.yaml, pkg/helmfiles/helpers_test_data/helmfiles/cert-manager/helmfile.yaml, pkg/helmfiles/helpers_test_data/helmfiles/jx/helmfile.yaml, pkg/helmfiles/helpers_test_data/helmfiles/jx/helmfiles/nested/helmfile.yaml, pkg/helmfiles/helpers_test_data/helmfiles/nginx/helmfile.yaml
Noticed issues with `jx gitops helmfile report` where namespaces were being reported twice. Seems that `GatherHelmfiles()` is both recursively finding a nested helmfile and appending it, but then also appending the same file by calculating it's location.
Removing the calculation resolves the issue but highlighted another issue in `jx gitops helmfile resolve` where if both a "jx3" and "jenkins-x" repository were found then only one was removed. This has also been fixed.
=> fix: issue with duplicate helmfiles being returned

pkg/plugins/versions.go
In particular to get the k8s libraries upgraded from 0.24 to 0.26
=> chore: upgrade kpt

pkg/plugins/versions.go
[v0.149.0](https://github.com/helmfile/helmfile/releases/tag/v0.149.0) is the latest version which avoids the backwards-incompatible logic in https://github.com/helmfile/helmfile/pull/592, but contains the fix in https://github.com/helmfile/helmfile/pull/499 which unblocks me from using `export HELMFILE_USE_SELECTORS = true` in my bootjob Makefile.
=> chore: upgrade helmfile to 0.149.0

pkg/cmd/pr/comment/comment.go, pkg/cmd/pr/comment/comment_test.go
This PR allows to choose between 3 different comment strategies:
- create (to always create a comment, this is the default strategy and the one used before)
- create-if-not-exists (to create a comment only if its content doesn't already exist on the associated PR)
- delete-and-create (to delete comment(s) if the content is similar and create the comment again
The check / deletion is only done to comment with similar Author Login :ok_hand:  
Examples:
Create Strategy:
```
jx-gitops pr comment -s create -c ':star:TEST COMMENT:star:'
commented on pull request #22 on repository xxx/test-comment
```
Create If Not Exists Strategy
```
jx-gitops pr comment -s create-if-not-exists -c ':star:TEST COMMENT:star:'
Similar comment already exists on pull request #22 on repository xxx/test-comment
``` …
=> feat(comment): allow to choose between 3 comment strategies

pkg/apis/gitops/v1alpha1/kpt_strategy_types.go, pkg/cmd/helmfile/report/report.go
jx gitops helmfile report can be quite slow. This should improve the performance quite a bit.
This is done by checking only once for each repository whether it is added and at the same time also load the index file. The chart metadata is then fetched from the index file directly instead of executing `helm show chart`.
=> Speed up helmfile report

.lighthouse/jenkins-x/release.yaml
related to: https://github.com/jenkins-x-plugins/jx-gitops/pull/956
needed to make release pipeline pass
=> ci: update release-binary golang version to 1.22.1

.github/workflows/codeql-analysis.yml, .github/workflows/plugins-pr.yaml, .lighthouse/jenkins-x/pullrequest.yaml, .lighthouse/jenkins-x/release.yaml, go.mod, go.sum
related to https://github.com/jenkins-x/jx/pull/8663
=> chore: use go 1.22

.goreleaser.yml
Nobody is downloading any arm or windows/arm64 binaries, so to save resources we stop building those
Statistics where fetched using https://qii404.me/github-release-statistics/
The one download of most resources aught to be down to something in the build process.
=> fix: reduce number of binaries to build

pkg/cmd/helm/mirror/mirror.go
`jx gitops helm mirror` does not push to the destination repository, as expected and specified in the documentation.
THis PR creates a `--no-push` flag, which defaults to `true`. This preserves the current behaviour, preventing this becoming a breaking change. This also fixes incorrect documentation.
=> chore: add --no-push flag; set logic for mirror to git push

pkg/cmd/helm/release/release_test.go, pkg/sourceconfigs/helpers.go, pkg/variablefinders/requirements.go, pkg/variablefinders/requirements_test.go
Use `PartialCloneClusterRepo` (from following addition to `jx-helpers` - https://github.com/jenkins-x/jx-helpers/pull/420) to attempt sparse and partial clone of the upstream cluster repository, as only the `.jx/gitops/source-config.yaml` file is required when finding requirements with `variablefinders`.
This change impacts the speed of `jx gitops helm release` and `jx gitops variables` commands when the upstream git provider supports `git-sparse-checkout`, in addition to the `--filter=blob:none` and `--depth=1` flags. Falls back to a full clone if neither are supported.
Picking a real example that is used for the following `jx-variables` pipeline task step - https://github.com/jenkins-x/jx3-pipeline-catalog/blob/b14ab0afd073539a25e5f2cee342f1e99537b46a/tasks/csharp/pullrequest.yaml#L27-L3 …
=> feat: attempt partial clone of cluster repo when loading requirements

pkg/cmd/helm/release/release_test.go, pkg/variablefinders/requirements.go
Requirements config file is needed `jx-requirements.yml` as well as `.jx/gitops/source-config.yaml` - add the former when doing a sparse checkout.
Note: tests are failing as only the "clone" step is run: https://github.com/jenkins-x-plugins/jx-gitops/blob/main/pkg/fakerunners/git_cloner.go
=> fix: Check out jx-requirements.yml from cluster repo upon sparse checkout

Dockerfile-preview, pkg/cmd/helm/build/build.go, pkg/cmd/helm/build/build_test.go, pkg/cmd/helm/build/testdata/has_charts/charts/myapp/Chart.yaml, pkg/cmd/helm/release/release.go, pkg/cmd/helm/release/release_test.go, pkg/cmd/helm/release/testdata/charts/myapp/Chart.yaml, pkg/cmd/plugin/upgrade/upgrade.go
This adds support for building & releasing helm charts that have dependencies on other helm charts. 
The use case is to make an umbrella helm chart containing a number of charts configured to work together as one deployable unit. 
I was only able to make this work by adding aws docker credential helper to the jx-gitops container. 
To add login credentials into a helmfile, you may pass environment variables like "REPO_NAME_PASSWORD", where REPO_NAME is the short name used to identify the repository in the helmfile.  
I guess it can be done, but to me it seems adding docker credential helpers makes it a lot easier.
=> Support OCI in helm charts with dependencies

pkg/cmd/helmfile/resolve/resolve.go, pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/helmfile_multi_subfolder/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/helmfile_subfolder/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/helmfile_subfolder/expected-secret-infra-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/local-secrets/expected-jx-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/remote-chart/expected-nginx-helmfile.yaml, pkg/cmd/helmfile/resolve/testdata/remote-cluster/expected-nginx-helmfile.yaml
This is useful when changing from values.yaml to values.yaml.gotmpl or when changeing repository for chart and moving values file along
=> fix: prune reference to any values files removed from version stream

pkg/cmd/repository/create/create.go, pkg/cmd/root.go
Since cobra only use the usage string up until the first space as command name in help I set an annotation which is used as is.
Also removing faulty example for `jx gitops repository create`
=> fix: correct usage of sub commands

pkg/plugins/versions.go
Helmfile version in jx-promote and jx-gitops are not matching 
https://github.com/jenkins-x-plugins/jx-promote/blob/4d9a914b6d5fdd5b3afc3345d5ab08c84d0d512e/go.mod#L8
https://github.com/jenkins-x-plugins/jx-gitops/blob/2cf70da50c5972e842c2d67430aaeb0abf511e4b/pkg/plugins/versions.go#L28
This is causing the PR created by jx-promote plugin to fail
=> chore: Update helmfile version

go.mod, go.sum, pkg/cmd/gc/activities/activities.go, pkg/cmd/gc/activities/activities_test.go
related to https://github.com/jenkins-x/jx/issues/8683
jx gitops is now converting properly to Tekton v1 instead of old v1beta1
=> Chore use latest lighthouse client with tekton 0.69.1
